Dende\MultidatabaseBundle\Entity\Tenant:
  type: entity
  table: tenants
  repositoryClass: Dende\MultidatabaseBundle\Entity\TenantRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  fields:
    host:
      type: string
      nullable: false
      length: 255
    dbname:
      type: string
      nullable: false
      length: 255
    user:
      type: string
      nullable: false
      length: 255
    password:
      type: string
      nullable: false
      length: 255
    subdomain:
      type: string
      nullable: false
      length: 255